# Usage:
# docker-compose build && docker-compose up
version: '2'

services:
  docker-hugo:
    image: talmai/docker-hugo
    build:
      context: .
      dockerfile: Dockerfile-hugo
    expose:
      - 1313
    ports:
      - '1313:1313'
    volumes:
      - ./output:/output
      - ./test-src:/src
    environment:
      HUGO_REFRESH_TIME: 3600
      HUGO_WATCH: "true"
    container_name: hugo

